config/routes.rb
Rails.application.routes.draw do

  root 'grayscales#index'

  resources :grayscales

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drop.rb
class Drop < ApplicationRecord

  validates :title, presence: true
  validates :reason, presence: true
  validates :p_key, presence: true, uniqueness: true, length: { is: 42 }
  
end

app/models/grayscale.rb
class Grayscale < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/grayscales_controller.rb
class GrayscalesController < ApplicationController
  layout "grayscale"

  def index
   @grayscale = Grayscale.new
   @grayscales = Grayscale.all
  end

  def new
    @grayscale = Grayscale.new
  end

  def create
    @grayscale = Grayscale.new(grayscale_params)
    @grayscale.save
    redirect_to root_path
    @grayscales = Grayscale.all
  end

  def edit
      @grayscale = Grayscale.find(params[:id])
  end

  def update
    @grayscale = Grayscale.find(params[:id])

      respond_to do |format|
            if @grayscale.update(grayscale_params)
              format.html { redirect_to grayscales_path notice: 'User was successfully created.' }
              format.json { render :show, status: :created, location: @grayscale }
              format.js { @status = "success"}
            else
              format.html { render :edit }
              format.json { render json: @grayscale.errors, status: :unprocessable_entity }
              format.js { @status = "fail" }
            end
          end
    @grayscales = Grayscale.all
  end

  def destroy
    @grayscale = Grayscale.find(params[:id])
    @grayscale.destroy
    redirect_to root_path
  end

  private

    def grayscale_params
      params.require(:grayscale).permit(
        :title,
        :reason,
        :p_key,
        :sns
        )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/grayscales/_about.html.erb
<section id="about" class="container content-section text-center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <h2>SHOWERとは</h2>
            <p>数あるair dropを一人のMyetherwalletに集め<a href="https://ja.wikipedia.org/wiki/%E3%83%99%E3%83%BC%E3%82%B7%E3%83%83%E3%82%AF%E3%82%A4%E3%83%B3%E3%82%AB%E3%83%A0">ベーシックインカム</a>のようなシステムを構築することを目的として作られたアプリ  </p>
            <p>アプリ名はmany drops make a showerからきている<br>たくさんのair dropを集め、金の雨を降らせよう</p>
            <p>面白い人たちから一人選んでちょっとアシストしてみよう<br>一番簡単なair drop(３ step)を下のリンクにまとめておいた</p>
        </div>
    </div>
</section>

app/views/grayscales/_contact.html.erb
<section id="contact" class="container content-section text-center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <h2>Contact SHOWER stuff</h2>
            <p>Feel free to email us to provide some feedback on our templates, give us suggestions for new templates and themes, or to just say hello!</p>
            <p><a href="https://www.facebook.com/daisuke.kuraishi">feedback@kuraishi daisuke.com</a>
            </p>
            <ul class="list-inline banner-social-buttons">
                <li>
                    <a href="https://twitter.com/kuranohu" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                </li>
                <li>
                    <a href="https://github.com/DaisukeKuraishi" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                </li>
                <li>
                    <a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                </li>
            </ul>
        </div>
    </div>
</section>

app/views/grayscales/_download.html.erb
<br>
<br>
<br>
<section id="download" class=" text-center">
    <div class="download-section">
        <div class="container">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>air drop link</h2>
                <p></p>
                <a href="http://kurokura.blog.jp/archives/8173288.html" class="btn btn-default btn-lg">Visit Link Page</a>
            </div>
        </div>
    </div>
</section>

app/views/grayscales/_edit.html.erb
<%= form_for(@grayscale, remote: true) do |f| %>
<div class="modal-dialog">
  <div class="modal-content">
    <div class="col-md-8 col-md-offset-2">
  <%= form_with model: grayscale, local: true do |form| %>
    <div class="form-group">
      <%= form.label :title %><br>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :reason %><br>
      <%= form.text_field :reason, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :p_key %><br>
      <%= form.text_field :p_key, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :sns %><br>
      <%= form.text_field :sns, class: "form-control" %>
    </div>
  </div>
</div>

app/views/grayscales/_footer.html.erb
<footer>
    <div class="container text-center">
        <p>Copyright &copy; Your Website <%= Time.now.year %></p>
    </div>
</footer>

app/views/grayscales/_form2.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <%= form_with(model: @grayscale,remote: true) do |form| %>

    <% if @grayscale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grayscale.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% grayscale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">New message</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">

      <div class="form-group field">
        <%= form.label :title , class: "form-control-label"%>
        <%= form.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group field">
        <%= form.label :reason , class: "form-control-label"%>
        <%= form.text_field :reason, class: "form-control" %>
      </div>
      <div class="form-group field">
        <%= form.label :p_key , class: "form-control-label"%>
        <%= form.text_field :p_key, class: "form-control" %>
      </div>
      <div class="form-group field">
        <%= form.label :sns , class: "form-control-label"%>
        <%= form.text_field :sns, class: "form-control" %>
      </div>
    </div>
    <div class="modal-footer actions">
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      <%= form.submit class: "btn btn-default"%>
    </div>
    <% end %>
  </div>
</div>

app/views/grayscales/_header.html.erb
<header class="intro">
    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h1 class="brand-heading">SHOWER</h1>
                    <p class="intro-text">金なんて知らないうちに貯まってたらいいじゃん<br>もうそのぐらいの価値しかない</p>
                    <a href="#about" class="btn btn-circle page-scroll">
                        <i class="fa fa-angle-double-down animated"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</header>

app/views/grayscales/_map.html.erb
<div id="map">
	    <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;aq=0&amp;oq=twitter&amp;sll=28.659344,-81.187888&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;t=m&amp;z=15&amp;iwloc=A&amp;output=embed"></iframe>
    <br />
    <small>
        <a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;aq=0&amp;oq=twitter&amp;sll=28.659344,-81.187888&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;t=m&amp;z=15&amp;iwloc=A"></a>
    </small>
    </iframe>
</div>

app/views/grayscales/_navigation.html.erb
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top">
                <i class="fa fa-play-circle"></i>  <span class="light">Start</span> Basic income
            </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <a class="page-scroll" href="#about">About</a>
                </li>
                <li>
                    <a class="page-scroll" href="#download">Air drop link</a>
                </li>
                <li>
                    <a class="page-scroll" href="#contact">理由一覧</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/grayscales/_save.js.erb
$("#grayscale-index").html("<%= escape_javascript(render 'tr') %>")
$("#grayscale-modal").modal("hide")

app/views/grayscales/_shim.html.erb
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/grayscales/_tr.html.erb
<% @grayscales.each do |grayscale| %>
  <dl>
    <h4>タイトル : <%= grayscale.title %></h4>
    <h4>理由 : <%= grayscale.reason %></h4>
    <h4>公開鍵 : <%= grayscale.p_key %></h4>
    <h4>sns : <%= grayscale.sns %></h4>
    <%= link_to '削除', grayscale, class: "btn btn-default", method: :delete %> 　<%= link_to '編集', edit_grayscale_path(grayscale),remote: true, class: "btn btn-default" %>

    <br>
      <br>
      <br>
  </dl>
<% end %>

app/views/grayscales/create.js.erb
<% if @status == 'success' %>
$("tbody").append("<%= j(render("tr", grayscale: @grayscale)) %>");
<%  elsif @status == 'fail' %>
alert('error!');
<% end %>
$("#grayscale-modal").modal("hide");

app/views/grayscales/index.html.erb
	<%= render 'shim' %>
	<%= render 'navigation' %>
	<%= render 'header' %>
	<%= render 'about' %>
	<%= render partial: 'show',locals: { grayscales: @grayscales} %>
	<%= render 'download' %>
	<%= render partial: 'form',locals: { grayscale: @grayscale} %>
	<%= render 'contact' %>
	<%= render 'map' %>
	<%= render 'footer' %>
	<div id="grayscale-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shower3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/grayscale.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grayscale - Start Bootstrap Theme</title>
  <%= stylesheet_link_tag 'grayscale/manifest.css', media: 'all' %>
  <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <%= javascript_include_tag 'grayscale/manifest.js' %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

<%= yield %>

</body>
</html>